### ISSUE TITLE
Устанавливает профиль

### ISSUE THREAD

**Issue by Koheri66** [htmlacademy/vscode-profile-htmlacademy#15]

**Comment by nikolai-shabalin** [comment]
@Koheri66 , привет =)
Подскажи о чём этот issue?

**Comment by Koheri66** [comment]
Николай, добрый день. Это ошибочный. ПроститеУдачного дня!!!11 апр. 2024 г., в 09:48, Nikolai Shabalin ***@***.***> написал(а):﻿
@Koheri66 , привет =)
Подскажи о чём этот issue?
